const CHECKSUM_LENGTH_IN_BYTES = 4
const CHECKSUM_START_IN_BYTES = 8
const FOOTER_LENGTH_IN_BYTES = 5
const HEADER_LENGTH_IN_BYTES = 10
const POSITION_PRECISION = 10000000

module.exports = {
  CHECKSUM_LENGTH_IN_BYTES,
  CHECKSUM_START_IN_BYTES,
  FOOTER_LENGTH_IN_BYTES,
  HEADER_LENGTH_IN_BYTES,
  POSITION_PRECISION
}
